In [1]:
import pandas as pd

df = pd.read_csv("../data/updated_food_dataset.csv")
print(df.shape)
df.info()
df.head()

(400, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Food_ID      400 non-null    int64
 1   Name         400 non-null    object
 2   C_Type       400 non-null    object
 3   Veg_Non      400 non-null    object
 4   Describe     400 non-null    object
 5   price        400 non-null    float64
 6   mapped_type  400 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 22.0+ KB

,Food_ID,Name,C_Type,Veg_Non,Describe,price,mapped_type
0,1,summer squash salad,Healthy Food,veg,"white balsamic vinegar, lemon juice, lemon rin...",42.17,vegan
1,2,chicken minced salad,Healthy Food,non-veg,"olive oil, chicken mince, garlic (minced), oni...",40.35,sweet
2,3,sweet chilli almonds,Snack,veg,"almonds whole, egg white, curry leaves, salt, ...",15.55,sweet
3,4,tricolour salad,Healthy Food,veg,"vinegar, honey/sugar, soy sauce, salt, garlic ...",26.32,sweet
4,5,christmas cake,Dessert,veg,"christmas dry fruits (pre-soaked), orange zest...",23.60,sweet